### ISSUE TITLE
VSCode extension fails to install on M1 MacBook

### ISSUE THREAD

**Issue by aldonline** [decoupled/lambdragon#2]
* When installed, the extension will spawn a process and call `npm i` 
* This will build a few native extensions
* `deasync` fails to build

Possible Slns:
* Get rid of deasync? (transitive)

**Comment by aldonline** [comment]
@jtoar I removed several native dependencies in v0.0.48. LMK if this works for you

**Comment by jtoar** [comment]
@aldonline I got further than before:

![image](https://user-images.githubusercontent.com/32992335/126001692-177e62ed-e89b-44c0-b8e1-472d2ed1e794.png)

there's no deasync error in the output, and I can see the counter climbing on the left.

I tried following the rest of your instructions (i.e. running one of the playgrounds) and ran into another M1-related error:

![image](https://user-images.githubusercontent.com/32992335/126001944-f2fc51b1-62d9-4f39-bfc2-1ebbea7abcbd.png)

**Comment by jtoar** [comment]
fixed!

**Comment by aldonline** [comment]
Thanks @jtoar.
The second error is not lambdragon specific, but related to the Redwood extension. Tracked here --> https://github.com/decoupled/redwood-megarepo/issues/1
